# Generated by Django 5.1.1 on 2025-05-07 19:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispute",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Phone number of the reporter",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must start with +2519, 2519, 9, +2517, 2517, or 7 followed by 8 digits.",
                                regex="^(\\+)?(?P<country_code>251)?(?P<phone_number>[79]\\d{8})$",
                            )
                        ],
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Disputed amount in ETB",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Dispute amount."
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("needs_response", "Needs Response"),
                            ("in_review", "In Review"),
                            ("reviewed", "Reviewed"),
                            ("resolved", "Resolved"),
                        ],
                        default="needs_response",
                        help_text="Current status of the dispute",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the dispute",
                        null=True,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When the dispute was resolved", null=True
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        help_text="The transaction being disputed",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes",
                        to="wallets.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispute",
                "verbose_name_plural": "Disputes",
                "ordering": ["-created_at"],
            },
        ),
    ]
