# Generated by Django 5.1.1 on 2025-05-08 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_admin", "0001_initial"),
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="refund_transaction",
            field=models.OneToOneField(
                blank=True,
                help_text="The refund transaction created for this dispute",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispute_refund",
                to="wallets.transaction",
            ),
        ),
    ]
