# Generated by Django 5.1.1 on 2025-05-09 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_admin", "0002_dispute_refund_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispute",
            name="amount",
            field=models.BigIntegerField(
                help_text="Disputed amount in ETB",
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Dispute amount."
                    )
                ],
            ),
        ),
    ]
