services:
  redis:
    image: redis:alpine
    ports:
      - 6380:6379
  pg:
    image: postgres:alpine
    restart: always
    ports:
      - 5480:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - config/pg.env
    shm_size: 128mb
  app:
    build:
      context: .
    entrypoint: sh entrypoint-app.sh
    depends_on:
      - pg
      - redis
    volumes:
      - medias:/medias
      - static:/static
      - .:/app
    env_file:
      - config/app.env
    ports:
      - 8880:8000
volumes:
  medias:
  static:
  pg_data:
