# Generated by Django 5.1.1 on 2025-05-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="code",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
