# Generated by Django 5.1.1 on 2025-05-17 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0002_institution_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutionwallet",
            name="institution",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wallet",
                to="sandbox.institution",
            ),
        ),
    ]
