# Generated by Django 5.1.1 on 2025-05-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enterprises", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accessgrant",
            old_name="client_id",
            new_name="access_id",
        ),
        migrations.RenameField(
            model_name="accessgrant",
            old_name="client_secret",
            new_name="access_secret",
        ),
        migrations.RemoveField(
            model_name="accessgrant",
            name="redirect_uri",
        ),
        migrations.RemoveField(
            model_name="accessgrant",
            name="scope",
        ),
    ]
