# Generated by Django 5.1.1 on 2025-05-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprises", "0002_rename_client_id_accessgrant_access_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accessgrant",
            name="actions_call_back",
        ),
        migrations.AddField(
            model_name="enterprise",
            name="actions_call_back",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Actions Call Back"
            ),
        ),
        migrations.AlterField(
            model_name="accessgrant",
            name="access_id",
            field=models.CharField(max_length=255, verbose_name="Access ID"),
        ),
        migrations.AlterField(
            model_name="accessgrant",
            name="access_secret",
            field=models.CharField(max_length=255, verbose_name="Access Secret"),
        ),
    ]
