# Generated by Django 5.1.1 on 2025-05-12 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="due_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="billing",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
