# Generated by Django 5.1.1 on 2025-05-05 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="logo_id",
        ),
        migrations.AddField(
            model_name="business",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="files.filemeta",
            ),
        ),
    ]
