# Generated by Django 5.1.1 on 2025-03-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_email_confirmed",
            new_name="is_email_verified",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="is_verified",
            new_name="is_phone_verified",
        ),
        migrations.RemoveField(
            model_name="business",
            name="license",
        ),
        migrations.AddField(
            model_name="business",
            name="license_id",
            field=models.UUIDField(default="91859731-161a-4699-aaa5-93ba31efaad3"),
            preserve_default=False,
        ),
    ]
