# Generated by Django 5.1.1 on 2025-04-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="license_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
