# Generated by Django 5.1.1 on 2025-05-05 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_business_logo_id_business_logo"),
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="license_id",
        ),
        migrations.AddField(
            model_name="business",
            name="license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="business_license",
                to="files.filemeta",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="business",
                to="files.filemeta",
            ),
        ),
    ]
