# Generated by Django 5.1.1 on 2025-05-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_business_license_id_business_license_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdevice",
            name="id",
            field=models.CharField(
                editable=False, max_length=255, primary_key=True, serialize=False
            ),
        ),
    ]
