# Generated by Django 5.1.1 on 2025-04-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_category_service_categories_userdevice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdevice",
            name="device_id",
        ),
        migrations.AddField(
            model_name="userdevice",
            name="label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="services", to="accounts.category"
            ),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="id",
            field=models.CharField(
                max_length=255, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
