# Generated by Django 5.1.1 on 2025-03-19 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_verificationcode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="verificationcode",
            old_name="type",
            new_name="code_type",
        ),
    ]
