# Generated by Django 5.1.1 on 2025-05-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_userdevice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdevice",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
