# Generated by Django 5.1.1 on 2025-03-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_temporarycode"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationcode",
            name="is_used",
            field=models.BooleanField(default=True),
        ),
    ]
