# Generated by Django 5.1.1 on 2025-03-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_verificationcode_is_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationcode",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
    ]
