# Generated by Django 5.1.1 on 2025-04-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0002_transaction_to_wallet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="wallet",
            new_name="from_wallet",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="notes",
            new_name="remarks",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="type",
        ),
    ]
