# Generated by Django 5.1.1 on 2025-04-16 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_category_service_categories_userdevice"),
        ("wallets", "0003_rename_wallet_transaction_from_wallet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="business",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wallet",
                to="accounts.business",
            ),
        ),
    ]
