# Generated by Django 5.1.1 on 2025-05-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0003_accesskey"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accesskey",
            old_name="access_key",
            new_name="access_id",
        ),
    ]
