# Generated by Django 5.1.1 on 2025-03-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_usersubscription_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
