# Generated by Django 5.1.1 on 2025-05-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_alter_subscription_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="payment_type",
            field=models.CharField(
                choices=[("pre", "Prepaid"), ("post", "Postpaid")],
                default="pre",
                max_length=255,
            ),
        ),
    ]
