# Generated by Django 5.1.1 on 2025-05-05 12:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileMeta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=255)),
                ("public_url", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["created_at", "updated_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
    ]
