# Generated by Django 5.1.1 on 2025-05-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filemeta",
            name="public_url",
            field=models.URLField(max_length=255),
        ),
    ]
