# Generated by Django 5.1.1 on 2025-04-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_signedurl"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileMeta",
            fields=[
                (
                    "key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("public_url", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="FileModel",
        ),
        migrations.DeleteModel(
            name="SignedUrl",
        ),
    ]
