# Generated by Django 5.1.1 on 2025-04-04 00:15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="label",
            field=models.CharField(default="default", max_length=255),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
