# Generated by Django 5.1.1 on 2025-04-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_verificationcode_is_used"),
        ("apis", "0002_apikey_label_alter_apikey_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="hashed_key",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="apikey",
            unique_together={("business", "label")},
        ),
    ]
