- name: Reload Django application
  hosts: myhosts
  tasks:
    - name: Updating code base
      ansible.builtin.git:
        accept_hostkey: true
        clone: yes
        update: yes
        name: git@github.com:gumi-apps/bita_backend.git
        dest: app
        force: yes
    - name: Reload app Service
      become: true
      ansible.builtin.systemd_service:
        name: app
        state: reloaded
        enabled: true
    - name: Reload Nginx Service
      become: true
      ansible.builtin.systemd_service:
        name: nginx
        state: reloaded
        enabled: true
        daemon_reload: true
