# Generated by Django 5.1.1 on 2025-05-05 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("broadcast", "broadcast"),
                            ("dedicated", "dedicated"),
                        ],
                        default="broadcast",
                        max_length=255,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("inApp", "inApp"), ("push", "push")],
                        default="inApp",
                        max_length=255,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="notifications", to="auth.group"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "updated_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
    ]
