# Generated by Django 5.1.1 on 2025-05-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="transaction_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
